### ISSUE TITLE
odissei namespace

### ISSUE THREAD

**Issue by jrvosse** [firmao/urideref#2]
In your rdf:

`@prefix odissei: <http://example.com/odissei#> .  # Replace with your actual ODISSEI namespace
`

I propose we use `https://w3id.org/odissei/ns/ ` as the general odissei namespace, so for example
`https://w3id.org/odissei/ns/portal/` for metadata ABOUT the portal.

**Comment by firmao** [comment]
Done: Namespace replaced.
